# Generated by Django 2.2 on 2019-04-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePara',
        ),
    ]
